# Form implementation generated from reading ui file 'Name.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Name(object):
    def setupUi(self, Name):
        Name.setObjectName("Name")
        Name.resize(439, 227)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Name.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Name)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Name)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NameLabel = QtWidgets.QLabel(self.widget_2)
        self.NameLabel.setObjectName("NameLabel")
        self.horizontalLayout.addWidget(self.NameLabel)
        self.NameInput = QtWidgets.QLineEdit(self.widget_2)
        self.NameInput.setObjectName("NameInput")
        self.horizontalLayout.addWidget(self.NameInput)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Name)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(100, 0, 98, 50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Submit = QtWidgets.QPushButton(self.widget)
        self.Submit.setObjectName("Submit")
        self.verticalLayout_2.addWidget(self.Submit)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Name)
        self.Submit.clicked.connect(lambda : self.submit(Name)) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Name)
        self.Name_user = ''

    def retranslateUi(self, Name):
        _translate = QtCore.QCoreApplication.translate
        Name.setWindowTitle(_translate("Name", "Name"))
        self.NameLabel.setText(_translate("Name", "TextLabel"))
        self.Submit.setText(_translate("Name", "Submit"))
    def submit(self,name):
        self.Name_user = self.NameInput.text()
        if self.Name_user != '' : name.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Name = QtWidgets.QDialog()
    ui = Ui_Name()
    ui.setupUi(Name)
    Name.show()
    sys.exit(app.exec())
